spring.application.name=auth-service


spring.datasource.url = jdbc:postgresql://localhost:5432/authentication_db
spring.datasource.username= postgres
spring.datasource.password= mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.data.redis.host= localhost
spring.data.redis.host.port= 6379
